<a href="https://colab.research.google.com/github/athulkrishnaks107-Aurex/pandas/blob/main/DS_(PANDAS).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
data=[20,30,40,50]
s=pd.Series(data)      #creating data with series
print(s)

0    20
1    30
2    40
3    50
dtype: int64

In [ ]:
import pandas as pd
data=[20,30,40,50]
s=pd.Series(data,index=['a','b','c','d'])                 #adding index values as a,b,c,d
print(s)

a    20
b    30
c    40
d    50
dtype: int64

In [ ]:
data={"name":"athul","age":19}
s=pd.Series(data)
print(s)

name    athul
age        19
dtype: object

In [ ]:
data=[1,2,3,4,5]
s=pd.Series(data)
print(s.loc[1])                      #loc is used to call a specific position

2

In [ ]:
data=[1,2,3,4,5]
s=pd.Series(data)
print(s.loc[1:4:1])                      #it can be use as slicing

1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
data=[1,2,3,4,5]
s=pd.Series(data,index=['a','b','c','d','e'])
print(s.iloc[:2])

a    1
b    2
dtype: int64

In [ ]:
data=[10,20,30,40,50]
s=pd.Series(data,index=['a','b','c','d','e'])
a=s[s>30]
print(a)
print(s.loc['a':'b'])
print(s.iloc[:2])

d    40
e    50
dtype: int64
a    10
b    20
dtype: int64
a    10
b    20
dtype: int64

In [ ]:
import pandas as pd
data=[10,20,30,40,50]
s=pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
sales=pd.Series([1200,850,1500,950,2000],index=["Monday","Tuesday","Wednesday","Thursday","Friday"])
print(sales)

max=sales.max()
print("\n Maximum sales =",max)

min=sales.min()
print("\n Minimum sales =",min)

lessthan1000=sales[sales<1000]
print("\n Days with sales less than 1000 =",lessthan1000)

Monday       1200
Tuesday       850
Wednesday    1500
Thursday      950
Friday       2000
dtype: int64

 Maximum sales = 2000

 Minimum sales = 850

 Days with sales less than 1000 = Tuesday     850
Thursday    950
dtype: int64

In [ ]:
import pandas as pd
data=[20,20,30,30,50,60,60,80]
ar=pd.Series(data)
print(ar)
print("\n",ar.unique())                 #it shows unique numbers once only
print("\n",ar.nunique())                #it shows total unique numbers
print("\n",ar.value_counts())           #it shows how many times a number is repeated

0    20
1    20
2    30
3    30
4    50
5    60
6    60
7    80
dtype: int64

 [20 30 50 60 80]

 5

 20    2
30    2
60    2
50    1
80    1
Name: count, dtype: int64

In [ ]:
data=[70,None,30,None,60,60,80]
ar=pd.Series(data)
print(ar)
print('\n',ar.isnull())        #it shows the given value is null or not
print('\n',ar.notnull())       #it shows the given value is number or not
print('\n',ar.fillna(0))       #it fill none values by given number (0)
print('\n',ar.dropna())        #it delet none values and then print

0    70.0
1     NaN
2    30.0
3     NaN
4    60.0
5    60.0
6    80.0
dtype: float64

 0    False
1     True
2    False
3     True
4    False
5    False
6    False
dtype: bool

 0     True
1    False
2     True
3    False
4     True
5     True
6     True
dtype: bool

 0    70.0
1     0.0
2    30.0
3     0.0
4    60.0
5    60.0
6    80.0
dtype: float64

 0    70.0
2    30.0
4    60.0
5    60.0
6    80.0
dtype: float64

In [2]:
import pandas as pd
marks=pd.Series([78,45,89,67,92,45,56,78,None,34],index=["anu","rahul","meera","arun","neha","vishnu","diya","akhil","riya","kiran"])
print(marks)
print("\nNumber of students:",len(marks))
print("\nhighest mark =",max(marks))

anu       78.0
rahul     45.0
meera     89.0
arun      67.0
neha      92.0
vishnu    45.0
diya      56.0
akhil     78.0
riya       NaN
kiran     34.0
dtype: float64

Number of students: 10

highest mark = 92.0

In [3]:
import numpy as np
data={"name":["alice","bob","charlie","david","emma"],
      "age":[20,21,19,22,20],
      "marks":[85,75,np.nan,90,65],
      "attendance":[95,80,75,np.nan,88],
      "city":['kochi',"delhi","mumbai","kochi","chennai"]
}

df=pd.DataFrame(data)
print(df)


#BASIC INFORMATION

print("\nFirst 3 rows:")
print(df.head(3))

print("\nLast 2 rows: ")
print(df.tail(2))

print("\nshape= ",df.shape)

print("\ncolumns= ",df.columns)

print("\ndatatype= ",df.dtypes)

print("\nName and marks:")
print(df[["name","marks"]])

print("\nRows 1 to 3,Name and Marks(using loc):")           #loc can print a specific position
print(df.loc[0:3,["name","marks"]])

print("\nRows 1 to 3(usingiloc)")                           #iloc cannot print a specific position,it printsn the whole values
print(df.iloc[0:3])

print("\nstudents with marks greater than 75:")
print(df[df["marks"]>75])

print("\nstudents from kochi:")
print(df[df["city"]=="kochi"])

print("\nstudents with no attendance:")
print(df[df["attendance"].isnull()])

print("\nstudents with marks > 70 AND attendance > 80:")
print(df[(df["marks"]>70) & (df["attendance"]>80)])


#-----MATHEMATICAL OPERATIONS-----

print("\nmarks + 5:")
print(df["marks"]+5)

print("\nmarks * 2:")
print(df["marks"]*2)

print("\nAverage marks:")
print(df["marks"].mean())

print("\nMaximum marks:")
print(df["marks"].max())

print("\nMinimum marks:")
print(df["marks"].min())

print("\ntotal marks:")
print(df["marks"].sum())

#-----------RENAMING-----------

df_rename = df.rename(columns={"marks":"scores",
                               "attendance":"attendance_percentage"})
print("\renamed dataframe:")
print(df_rename)

print("\nmissing values:")
print(df.isna())

print("\nnumber of missing values:")
print(df.isna().sum())

#-------FORWARD FILL-------
df_forward=df.copy()
df_forward=df_forward.ffill()
print("\nforward fill:")
print(df_forward)

#-------BACKWARD FILL-------
df_backward=df.copy()
df_backward=df_backward.fillna(method="bfill")
print("\nbackward fill:")
print(df_backward)

      name  age  marks  attendance     city
0    alice   20   85.0        95.0    kochi
1      bob   21   75.0        80.0    delhi
2  charlie   19    NaN        75.0   mumbai
3    david   22   90.0         NaN    kochi
4     emma   20   65.0        88.0  chennai

First 3 rows:
      name  age  marks  attendance    city
0    alice   20   85.0        95.0   kochi
1      bob   21   75.0        80.0   delhi
2  charlie   19    NaN        75.0  mumbai

Last 2 rows:
    name  age  marks  attendance     city
3  david   22   90.0         NaN    kochi
4   emma   20   65.0        88.0  chennai

shape=  (5, 5)

columns=  Index(['name', 'age', 'marks', 'attendance', 'city'], dtype='object')

datatype=  name           object
age             int64
marks         float64
attendance    float64
city           object
dtype: object

Name and marks:
      name  marks
0    alice   85.0
1      bob   75.0
2  charlie    NaN
3    david   90.0
4     emma   65.0

Rows 1 to 3,Name and Marks(using loc):
      name  marks
0    alice   85.0
1      bob   75.0
2  charlie    NaN
3    david   90.0

Rows 1 to 3(usingiloc)
      name  age  marks  attendance    city
0    alice   20   85.0        95.0   kochi
1      bob   21   75.0        80.0   delhi
2  charlie   19    NaN        75.0  mumbai

students with marks greater than 75:
    name  age  marks  attendance   city
0  alice   20   85.0        95.0  kochi
3  david   22   90.0         NaN  kochi

students from kochi:
    name  age  marks  attendance   city
0  alice   20   85.0        95.0  kochi
3  david   22   90.0         NaN  kochi

students with no attendance:
    name  age  marks  attendance   city
3  david   22   90.0         NaN  kochi

students with marks > 70 AND attendance > 80:
    name  age  marks  attendance   city
0  alice   20   85.0        95.0  kochi

marks + 5:
0    90.0
1    80.0
2     NaN
3    95.0
4    70.0
Name: marks, dtype: float64

marks * 2:
0    170.0
1    150.0
2      NaN
3    180.0
4    130.0
Name: marks, dtype: float64

Average marks:
78.75

Maximum marks:
90.0

Minimum marks:
65.0

total marks:
315.0
enamed dataframe:
      name  age  scores  attendance_percentage     city
0    alice   20    85.0                   95.0    kochi
1      bob   21    75.0                   80.0    delhi
2  charlie   19     NaN                   75.0   mumbai
3    david   22    90.0                    NaN    kochi
4     emma   20    65.0                   88.0  chennai

missing values:
    name    age  marks  attendance   city
0  False  False  False       False  False
1  False  False  False       False  False
2  False  False   True       False  False
3  False  False  False        True  False
4  False  False  False       False  False

number of missing values:
name          0
age           0
marks         1
attendance    1
city          0
dtype: int64

forward fill:
      name  age  marks  attendance     city
0    alice   20   85.0        95.0    kochi
1      bob   21   75.0        80.0    delhi
2  charlie   19   75.0        75.0   mumbai
3    david   22   90.0        75.0    kochi
4     emma   20   65.0        88.0  chennai

backward fill:
      name  age  marks  attendance     city
0    alice   20   85.0        95.0    kochi
1      bob   21   75.0        80.0    delhi
2  charlie   19   90.0        75.0   mumbai
3    david   22   90.0        88.0    kochi
4     emma   20   65.0        88.0  chennai

/tmp/ipykernel_4900/1211014317.py:90: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_backward=df_backward.fillna(method="bfill")

'FORWARD FILL' IS USED TO FILL THE NULL VALUE WITH THE PREVIOS VALUE

'BACKWARD FILL' IS USED TO FILL THE NULL VALUES WITH VALUE AFTER NULL

In [ ]:
df=pd.read_csv("/content/nigeria_messy_sales_dataset.csv")
df

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,NaN,NaN,NaN,2025-04-27,Online,NaN
1,Allison Hill,Lagos,Headphones,NaN,267992.94,NaN,2024-03-15,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
2,Noah Rhodes,Anambra,Keyboard,NaN,42364.41,NaN,2024-12-10,NaN,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed
3,Angie Henderson,Delta,Keyboard,NaN,279444.94,NaN,2024-04-05,NaN,74503887-48d9-4846-95c5-51fcfba57cc8
4,Daniel Wagner,Delta,Tablet,NaN,95899.74,NaN,2025-01-12,NaN,8639bd41-8b15-4d94-a42d-0cd7fd359f6a
...,...,...,...,...,...,...,...,...,...
545,Zachary Mitchell,Ekiti,Monitor,6.0,23989.09,143934.54,2025-07-07,Wholesale,b9744cde-d259-4960-aee3-560792ea1324
546,NaN,Katsina,Tablet,NaN,223764.24,NaN,2025-02-11,Wholesale,NaN
547,Katherine Martinez,Bauchi,Phone,NaN,104084.92,NaN,2025-05-18,Retail,61fa8e7a-078c-46ce-bf02-23bc651ea252
548,Jodi Roach,Niger,Charger,NaN,29756.89,NaN,2025-06-29,Direct,5a9c0679-2c3d-47e2-ad39-da75aee70ab2
549,Brandon Fleming,imo,Camera,NaN,70027.13,NaN,2024-02-20,NaN,46653497-2fe9-42aa-a886-a01136f7a26c

In [ ]:
#1
print("number of rows and columns",df.shape)

number of rows and columns (550, 9)

In [ ]:
#2
df.head(7)

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,NaN,NaN,NaN,2025-04-27,Online,NaN
1,Allison Hill,Lagos,Headphones,NaN,267992.94,NaN,2024-03-15,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
2,Noah Rhodes,Anambra,Keyboard,NaN,42364.41,NaN,2024-12-10,NaN,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed
3,Angie Henderson,Delta,Keyboard,NaN,279444.94,NaN,2024-04-05,NaN,74503887-48d9-4846-95c5-51fcfba57cc8
4,Daniel Wagner,Delta,Tablet,NaN,95899.74,NaN,2025-01-12,NaN,8639bd41-8b15-4d94-a42d-0cd7fd359f6a
5,Cristian Santos,Oyo,Camera,NaN,118189.90,NaN,2023-08-30,Direct,225aed6c-f045-4043-a3a6-8a707e710b55
6,Connie Lawrence,Rivers,Tablet,36.0,185141.90,6665108.4,2024-09-10,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e

In [ ]:
df.tail(5)

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
545,Zachary Mitchell,Ekiti,Monitor,6.0,23989.09,143934.54,2025-07-07,Wholesale,b9744cde-d259-4960-aee3-560792ea1324
546,NaN,Katsina,Tablet,NaN,223764.24,NaN,2025-02-11,Wholesale,NaN
547,Katherine Martinez,Bauchi,Phone,NaN,104084.92,NaN,2025-05-18,Retail,61fa8e7a-078c-46ce-bf02-23bc651ea252
548,Jodi Roach,Niger,Charger,NaN,29756.89,NaN,2025-06-29,Direct,5a9c0679-2c3d-47e2-ad39-da75aee70ab2
549,Brandon Fleming,imo,Camera,NaN,70027.13,NaN,2024-02-20,NaN,46653497-2fe9-42aa-a886-a01136f7a26c

In [ ]:
#3
df[["Product","Units Sold","Unit Price","Total Sale"]]

        Product  Units Sold  Unit Price  Total Sale
0      KEYBOARD         NaN         NaN         NaN
1    Headphones         NaN   267992.94         NaN
2      Keyboard         NaN    42364.41         NaN
3      Keyboard         NaN   279444.94         NaN
4        Tablet         NaN    95899.74         NaN
..          ...         ...         ...         ...
545     Monitor         6.0    23989.09   143934.54
546      Tablet         NaN   223764.24         NaN
547       Phone         NaN   104084.92         NaN
548     Charger         NaN    29756.89         NaN
549      Camera         NaN    70027.13         NaN

[550 rows x 4 columns]

In [ ]:
#4
df["Units Sold"]>50

0      False
1      False
2      False
3      False
4      False
       ...
545    False
546    False
547    False
548    False
549    False
Name: Units Sold, Length: 550, dtype: bool

In [ ]:
#5
df["Unit Price"]>100000

0      False
1       True
2      False
3       True
4      False
       ...
545    False
546     True
547     True
548    False
549    False
Name: Unit Price, Length: 550, dtype: bool

In [ ]:
#6
df["Sales Channel"]=="Online"

0       True
1      False
2      False
3      False
4      False
       ...
545    False
546    False
547    False
548    False
549    False
Name: Sales Channel, Length: 550, dtype: bool

In [ ]:
#7
df["State"].unique()

array(['rivers', 'Lagos', 'Anambra', 'Delta', 'Oyo', 'Rivers', 'Imo',
       'Kano', 'plateau', 'Niger', 'Abuja', 'Enugu', 'Bauchi', 'Katsina',
       'lagos', 'Ekiti', 'Plateau', 'Kaduna', 'Sokoto', 'kano', 'Benue',
       'Osun', 'imo', 'Borno', 'enugu', 'anambra', 'katsina', 'delta',
       'Cross River', 'oyo', 'osun', 'kaduna', 'niger', 'borno', 'abuja',
       'bauchi', 'cross river', 'ekiti', 'sokoto', 'benue'], dtype=object)

In [ ]:
df["State"].nunique()

40

In [ ]:
#8
df["Sales Channel"].value_counts()

Sales Channel
Direct       124
Wholesale    111
Retail       108
Online       101
Name: count, dtype: int64

In [ ]:
#9
df.isnull().sum()

Customer Name     43
State              0
Product            0
Units Sold       395
Unit Price        55
Total Sale       413
Sale Date          0
Sales Channel    106
Order ID          40
dtype: int64

In [ ]:
#10
df.dropna()

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
6,Connie Lawrence,Rivers,Tablet,36.0,185141.90,6665108.40,2024-09-10,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e
11,Monica Herrera,Abuja,Laptop,3.0,153159.37,459478.11,2025-05-02,Retail,317304b5-c1dd-484a-aca5-8d95915a1c30
12,Jamie Arnold,Lagos,Tablet,43.0,147209.07,6329990.01,2023-11-10,Wholesale,a383889a-db2c-4ac8-9c67-83932ced3c0d
18,Holly Wood,lagos,Headphones,43.0,125253.81,5385913.83,2023-11-23,Direct,6231ee73-42c2-42eb-81bf-9e733f800385
19,Derek Zuniga,Imo,Headphones,77.0,92649.51,7134012.27,2025-03-18,Online,4459bd6e-c0f6-4229-b25d-42593c4b1eec
...,...,...,...,...,...,...,...,...,...
517,Judith Carter,Kano,Laptop,46.0,170251.85,7831585.10,2023-08-25,Wholesale,1ee89a4c-6811-44e2-9064-7c59774f6354
527,Monica Miller,Lagos,Laptop,47.0,5189.60,243911.20,2025-05-01,Retail,4c80d33a-ad5b-43c8-8c88-0714837217e0
537,Lawrence Harrington,Rivers,Monitor,16.0,254908.01,4078528.16,2025-07-05,Direct,15839b99-a50a-43dc-b004-e897a15b2e18
544,Mr. Justin Green III,Sokoto,KEYBOARD,65.0,206948.51,13451653.15,2023-12-02,Online,ec93e596-2b01-4723-8cf6-97a57603c36c
545,Zachary Mitchell,Ekiti,Monitor,6.0,23989.09,143934.54,2025-07-07,Wholesale,b9744cde-d259-4960-aee3-560792ea1324